name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            suffix: linux-amd64
          - os: windows-latest
            goos: windows
            suffix: windows-amd64
          - os: macos-13
            goos: darwin
            suffix: osx-amd64
          - os: macos-latest
            goos: darwin
            suffix: osx-arm64

    steps:
      - uses: actions/checkout@main
      - name: env
        run: bazel --version
      - name: Test on Windows
        if: matrix.goos == 'windows'
        run: bazel test --config=windows //test:tests
      - name: Test
        if: matrix.goos != 'windows'
        run: bazel test --config=osx //test:tests
